shell script

diff --git a/14_for_loop_ex b/14_for_loop_ex
--- a/14_for_loop_ex
+++ b/14_for_loop_ex
@@ -2,18 +2,20 @@
 
 movies=("Thanman" "AR" "auto" "seenu" "Ramu")
 
-# for i in ${movies[@]}
-# do
-#     if[ $i == "ABC" ]
-#     then
-#         echo "not found ABC"
-#         exit 1
-#     else
-#         echo $i
-#     fi
-# done
-
 for i in ${movies[@]}
 do
-   echo $i
+    if [ $i == "auto" ]
+    then
+        echo "not found ABC"
+        exit 1
+    else
+        echo $i
+    fi
 done
+
+# for i in ${movies[@]}
+# do
+#    echo $i
+# done
+
+
