shell script

diff --git a/14_for_loop_ex b/14_for_loop_ex
--- a/14_for_loop_ex
+++ b/14_for_loop_ex
@@ -3,14 +3,12 @@ movies=("Thanman" "AR" "auto" "seenu" "Ramu")
 
 for i in ${movies[@]}
 do
-        echo $i
-
-        if[ $i -eq "ABC" ]
-
-        then
-            exit 1
-        else
-            echo "not found"
-        fi
+    echo $i
+    if[ $i -eq "ABC" ]
+    then
+        exit 1
+    else
+        echo "not found"
+    fi
 done
 
